
(define (get-nest-level)
  (if (identifier-binding #'nest-level)
    (eval #'nest-level)
    0))

(define printf-orig printf)
(define (printf . args)
  (let ([nest-level (get-nest-level)])
    (for ([i (in-range nest-level)])
      (printf "| "))
    (apply printf args)))

(define-effect E1 ())
(define-effect E2 ())

(define (main)
  (printf "A1~%")
  (with-effect-handler
    (handler H1
      [(effect (E1) k1)
        (printf "(handle (E1) k1)~%")
        (printf "D1~%")
        (printf "(continue k1)~%")
        (continue k1 (void))
        (printf "(return-cont k1)~%")
        (printf "D2~%")])
    (printf "B1~%")
    (with-effect-handler
      (handler H2
        [(effect (E2) k2)
          (printf "(handle (E2) k2)~%")
          (printf "E1~%")
          (with-effect-handler
            (handler H3
              [(effect (E1) k3)
                (printf "(handle (E1) k3)~%")
                (printf "G1~%")
                (printf "(continue k3)~%")
                (continue k3 (void))
                (printf "(return-cont k3)~%")
                (printf "G2~%")])
            (printf "F1~%")
            (printf "(continue k2)~%")
            (continue k2 (void))
            (printf "(return-cont k2)~%")
            (printf "F2~%"))
          (printf "E2~%")])
      (printf "C1~%")
      (printf "(perform (E1))~%")
      (perform (E1))
      (printf "C2~%")
      (printf "(perform (E2))~%")
      (perform (E2))
      (printf "C3~%")
      (printf "(perform (E1))~%")
      (perform (E1))
      (printf "C4~%"))
    (printf "B2~%"))
  (printf "A2~%"))
